from os import environ

EVENTSTORE_API_URL = environ.get("EVENTSTORE_API_URL")
EVENTSTORE_API_TOKEN = environ.get("EVENTSTORE_API_TOKEN")
RAPIDPRO_URL = environ.get("RAPIDPRO_URL")
RAPIDPRO_TOKEN = environ.get("RAPIDPRO_TOKEN")
RAPIDPRO_BASELINE_SURVEY_COMPLETE_FLOW = environ.get(
    "RAPIDPRO_BASELINE_SURVEY_COMPLETE_FLOW"
)
