[tool.poetry]
name = "vaccine"
version = "0.1.0"
description = "Demo application for what a vaccine eligibility flow could look like"
authors = ["Praekelt.org <dev@praekelt.org>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/praekeltfoundation/vaccine-eligibility"
repository = "https://github.com/praekeltfoundation/vaccine-eligibility"

[tool.poetry.dependencies]
python = "^3.9"
aio-pika = "^6.7.1"
aioredis = "^1.3.1"
sanic = "^20.12.2"
prometheus-client = "^0.9.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
mypy = "^0.800"
flake8 = "^3.8.4"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-asyncio = "^0.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
addopts = "--cov=vaccine"
