[tool.poetry]
name = "vaccine"
version = "0.1.0"
description = "Demo application for what a vaccine eligibility flow could look like"
authors = ["Praekelt.org <dev@praekelt.org>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/praekeltfoundation/vaccine-eligibility"
repository = "https://github.com/praekeltfoundation/vaccine-eligibility"

[tool.poetry.dependencies]
python = "^3.9"
aio-pika = "^6.7.1"
aioredis = "2.0.0a1"
sanic = "~21.6"
prometheus-client = "^0.9.0"
aiohttp = {extras = ["speedups"], version = "^3.7.4"}
sentry-sdk = "^1.5.0"
phonenumberslite = "^8.12.21"
pycountry = "^20.7.3"
aiohttp-client-cache = "^0.5.2"
rapidfuzz = "^1.4.1"
holidays = "^0.11.2"
email-validator = "^1.1.3"
zbar-py = "^1.0.4"
opencv-python-headless = "^4.5.3"
beautifulsoup4 = "^4.10.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
isort = "^5.7.0"
mypy = "^0.800"
flake8 = "^3.8.4"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-asyncio = "^0.14.0"
pytest-sanic = "^1.9.1"
Faker = "^8.1.0"
locust = "^1.4.4"
sanic-testing = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
addopts = "--cov=vaccine"
