from os import environ

API_HOST = environ.get("API_HOST")
API_TOKEN = environ.get("API_TOKEN")
LOG_LEVEL = environ.get("LOG_LEVEL", "INFO")
YAL_BOT_LAUNCH_DATE = environ.get("YAL_BOT_LAUNCH_DATE", "2022-05-01")
CONTENTREPO_API_URL = environ.get("CONTENTREPO_API_URL")
CONTENTREPO_API_TOKEN = environ.get("CONTENTREPO_API_TOKEN")
AWS_MEDIA_URL = environ.get("AWS_MEDIA_URL")
MAX_AGE = int(environ.get("MAX_AGE", "122"))
PRIVACY_POLICY_PDF = environ.get("PRIVACY_POLICY_PDF", "1/sample.pdf")
EMERGENCY_NUMBER = environ.get("EMERGENCY_NUMBER", "XXX")
LOVELIFE_URL = environ.get("LOVELIFE_URL")
LOVELIFE_TOKEN = environ.get("LOVELIFE_TOKEN")
SERVICEFINDER_URL = environ.get("SERVICEFINDER_URL")
SERVICEFINDER_TOKEN = environ.get("SERVICEFINDER_TOKEN")
GOOGLE_PLACES_URL = "https://maps.googleapis.com"
GOOGLE_PLACES_KEY = environ.get("GOOGLE_PLACES_KEY")
RAPIDPRO_URL = environ.get("RAPIDPRO_URL")
RAPIDPRO_TOKEN = environ.get("RAPIDPRO_TOKEN")
USERTESTING_FLOW_UUID = environ.get("USERTESTING_FLOW_UUID")
AAQ_URL = environ.get("AAQ_URL")
AAQ_TOKEN = environ.get("AAQ_TOKEN")
SEGMENT_AIRTIME_FLOW_UUID = environ.get("SEGMENT_AIRTIME_FLOW_UUID")
QA_OVERRIDE_CURRENT_TIMESTAMP = environ.get("QA_OVERRIDE_CURRENT_TIMESTAMP", None)
STUDY_CONSENT_FORM_PDF = environ.get("STUDY_CONSENT_FORM_PDF", "1/sample.pdf")
LOCATION_STUDY_GROUP_LIMIT = int(environ.get("LOCATION_STUDY_GROUP_LIMIT", "430"))
FACEBOOK_SURVEY_INVITE_MEMBERS_URL = environ.get(
    "FACEBOOK_SURVEY_INVITE_MEMBERS_URL",
    "https://docs.google.com/forms/d/e/1FAIpQLScjbZEbIjQXMDdHbJTUCjxYnbRVP4D2p6kXQy74tXrIN6Qwww/viewform?usp=sf_link",
)
FACEBOOK_SURVEY_INVITE_SEEN_FEED_URL = environ.get(
    "FACEBOOK_SURVEY_INVITE_SEEN_FEED_URL",
    "https://docs.google.com/forms/d/e/1FAIpQLSe_YlROLiezkGFbdcK7HBA99ABrWvUcvZ20azvAEpQKHwr6kw/viewform?usp=sf_link",
)
