from os import environ

REAL411_URL = environ.get("REAL411_URL", "")
REAL411_TOKEN = environ.get("REAL411_TOKEN")
REAL411_IDENTIFIER = environ.get("REAL411_IDENTIFIER", "PRAEKELT_API")
WHATSAPP_URL = environ.get("WHATSAPP_URL", "")
WHATSAPP_TOKEN = environ.get("WHATSAPP_TOKEN", "")
HEALTHCHECK_URL = environ.get("HEALTHCHECK_URL", "")
HEALTHCHECK_TOKEN = environ.get("HEALTHCHECK_TOKEN", "")
