name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.8
        ports:
          - 5672:5672
      redis:
        image: redis:6.0
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        id: install-deps
        run: |
          uv sync --dev
      - name: Check formatting
        # Lints/tests should always run, even if other lints/tests have failed.
        if: success() || failure() && steps.install-deps.outcome == 'success'
        run: |
          uv run ruff format --check
      - name: Lint
        if: success() || failure() && steps.install-deps.outcome == 'success'
        run: |
          uv run ruff check
      - name: Run migrations
        if: success() || failure() && steps.install-deps.outcome == 'success'
        run: |
          uv run ./manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
      - name: Run tests
        if: success() || failure() && steps.install-deps.outcome == 'success'
        run: |
          uv run pytest -vv